name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install cucumber
      run: npm install --save-dev @cucumber/cucumber
      
    - name: Install cucumber
      run: npm init playwright@latest

    - name: Install cucumber
      run: npm install --save-dev @cucumber/pretty-formatter @cucumber/cucumber
      
    - name: Run tests with pretty formatter
      run: npx cucumber-js -f @cucumber/pretty-formatter
