name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install cucumber and playwright
      run: npm install cucumber playwright @cucumber/cucumber --save-dev

    - name: Install playwright
      run: npx playwright install

    - name: Install playwright test
      run: npm install @playwright/test --save-dev

    - name: Install pretty-formatter
      run: npm install --save-dev @cucumber/pretty-formatter @cucumber/cucumber
      
    - name: Run tests with pretty formatter
      run: npx cucumber-js -f @cucumber/pretty-formatter